### PR TITLE
More sensors and some corrections

### PR DESCRIPTION
**Pull request by Bascht74**
More sensors inserted, sequence unified. Example YAML Unified and supplemented, measurement units corrected, calculation logic for room temperature adapted, further extensions (Alarm & Config) prepared.

### CODE REVIEW

**Comment by Bascht74** [comment]
My first commit. I hope it is not too bad for the first one.
I moved some sensors up and down to get them all in the same order.

**Comment by the78mole** [comment]
Alter Schwede!!! Great Job! Thanks for that... I will try this instantly!

**Comment by jensgraef** [comment]
Wow!

**Comment by the78mole** [comment]
Just to make the comments to this PR complete... Some sensor names have been renamed (heating_circuit_1 has been prepended to the identifying names), which leads to errors when upgrading from the version before the PR.

**Pull request merged**
