### PR TITLE
Write warm water target temperature

### PR DESCRIPTION
**Pull request by jensgraef**
This merge requests adds a switch to toggle warm water heating between the modes auto and night. This allows to turn of warm water heating remotely e.g. when nobody is at home.

Futhermore this merge request adds a number control for the warm water target temperature.

See Readme for some words of caution about changing device parameters.

### CODE REVIEW

**Review by the78mole — APPROVED** [review]
I instantly updated my KM271-WiFi and it works... Only thing I need to understand is the Hot water Auto/Night switch. I see a change on the Buderus (it switches off/on the load pump for hot water), but I'm not sure, what is the long term effect.

**Comment by the78mole** [comment]
Great! This is what I searched for :-) Thanks Jens!

**Comment by Bascht74** [comment]
> I instantly updated my KM271-WiFi and it works... Only thing I need to understand is the Hot water Auto/Night switch. I see a change on the Buderus (it switches off/on the load pump for hot water), but I'm not sure, what is the long term effect.

If it is set to automatic, then the hot water control takes over the day and night operation of the heating circuit. If set to night, then it will not make new hot water.

This allows you to make hot water only once a day, for example at noon around 14:00, when the heating is least needed....

In addition, the ciculation is deactivated. Both helps to save heating costs.

In combination with the water temperature, you can run the ww-heating at 50 degrees during the week, for example, and increase it to 65 degrees one day a week (thermal disinfection). The lower water temperature will also save a few kWh/L per year again....

**Comment by Bascht74** [comment]
@jensgraef oh, didn’t see your answer…

**Comment by the78mole** [comment]
The only question many people have: "How do On and Off map to Auto and Night?"
I believe, selects would be a better/more intuitive solution, but currently, I have not enough time to dive deeply into the complexity of the code.

**Comment by Bascht74** [comment]
You are totally right. It temporarily solution. Jens is planing to do such things as select entity. 
But we can use switch entities for other stuff for sure…
Next week I am planing to add what is possible now…

**Pull request merged**
