### PR TITLE
Add hc1 room target temperature

### PR DESCRIPTION
**Pull request by jensgraef**

### CODE REVIEW

**Comment by jensgraef** [comment]
This pull request is based on #47. Please do not merge before #47.

**Review by the78mole — APPROVED** [review]

**Comment by the78mole** [comment]
@jensgraef could you have a quick look on the conflict?

**Comment by jensgraef** [comment]
This is already in main as it was also included in #51.
So nothing more to do here :)

**Comment by the78mole** [comment]
OK 🤣

**Pull request closed without merging**
