### PR TITLE
Fix handling of negative temperature offsets

### PR DESCRIPTION
**Pull request by jensgraef**
Fix rounding issue when setting a value leading to setting values 0.5° higher. 
Fix parsing issue leading to wrong values in home assistant when using negative offsets.

This PR solves #75

### CODE REVIEW

**Comment by jensgraef** [comment]
I tested this by changing HK1 offset temperatures through home assistant and verifying on the control unit of the heater and also the other way around by setting temperatures on the control unit and checking home assistant. Everything looks fine for positive values, negative values and 0.

**Comment by the78mole** [comment]
Wow @jensgraef, that was fast. I'll try it out now on my Buderus and will finish the review.

**Review by the78mole — APPROVED** [review]
After testing, looks very promising. Changed temperature on Buderus to a negative room temp offset, reflects correctly back into UI and vice versa. Also from the logs, everything seems to be right.

**Comment by the78mole** [comment]
Thanks @jensgraef 😘

**Pull request merged**
