### PR TITLE
add boiler runtime calculation

### PR DESCRIPTION
**Pull request by jensgraef**
Assemble boiler runtime from separate values

### CODE REVIEW

**Comment by jensgraef** [comment]
Open issues: 
1. the value if strange at for my heater
2. I'm not sure whether it's minutes or hours
3. the order in which the components of the number are updated is unclear

**Comment by qschneider** [comment]
i calculated those values in nodeRED this way.
They come as unsigned_int nothing fancy.
The only complication is, that they don't come in order, but rather the values as they change, just in the initial sensor request, you get them ordered.
Another consideration is the buffer-change from 255 -> 0 and increment of the next higher Byte, as this needs to be taken care of.

            // Betriebsstunden berechnen
            case "0x8836":
            case "0x8837":
            case "0x8838":
                flow.set(msg.km271, km271_value);
                if (flow.get("0x8836") !== undefined && flow.get("0x8837") !== undefined ) {
                    const Betriebsminuten1 = flow.get("0x8836") * 65536 + flow.get("0x8837") * 256 + flow.get("0x8838");
                    flow.set("Betriebsminuten1", Betriebsminuten1);
                    flow.set("Betriebsstunden1", Math.floor(Betriebsminuten1 / 60));
                }
                break;

**Comment by jensgraef** [comment]
Thanks @qschneider 
So, issue 2 solved: It's minutes.
I'll investigate the strange values further when I've got some time

**Comment by qschneider** [comment]
{ BLZ2S0 , false, SensorType::MULTI_PARAMETER_UNSIGNED_INTEGER, 0x0200, "Brennerlaufzeit 2 Stunden 0", "h"},

the "h" stands for hours? shouldn't it be empty oder "min" ?

**Comment by jensgraef** [comment]
> { BLZ2S0 , false, SensorType::MULTI_PARAMETER_UNSIGNED_INTEGER, 0x0200, "Brennerlaufzeit 2 Stunden 0", "h"},
> 
> the "h" stands for hours? shouldn't it be empty oder "min" ?
Yeah, thanks for mentioning it - changed it to m

**Comment by jensgraef** [comment]
issue 1 solved: code fixed

**Comment by jensgraef** [comment]
What's not yet taken care of is the possible discontinuity when one value overflows.
But that's just a short glitch - so let's merge an fix issues later :)

**Review by the78mole — APPROVED** [review]
Getestet und passt!

**Pull request merged**
